-- 삭제
DROP TABLE RESERVATION
CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_RESERV;

-- 생성
CREATE TABLE RESERVATION(
	SEQ NUMBER(8) PRIMARY KEY,
	ID VARCHAR2(20) NOT NULL,
	NAME VARCHAR2(20) NOT NULL,
	BIRTHDATE VARCHAR2(20) NOT NULL,
	PHONE VARCHAR2(20) NOT NULL,
	EMAIL VARCHAR2(30) NOT NULL,
	ADDRESS VARCHAR2(100) NOT NULL,
	RECEIVE VARCHAR2(30) NOT NULL,
	QTY NUMBER(8) NOT NULL,
	TOTAL_PRICE NUMBER(20) NOT NULL,
	PAY_METHOD VARCHAR2(30) NOT NULL,
	DEL NUMBER(2)
);

-- 무결성
ALTER TABLE RESERVATION 
ADD CONSTRAINT FK_RESERV_ID FOREIGN KEY (ID)
REFERENCES MEMBER(ID);


-- 시퀀스
CREATE SEQUENCE SEQ_RESV
START WITH 1
INCREMENT BY 1;

SELECT * FROM RESERVATION;
