DROP TABLE MEMBER
CASCADE CONSTRAINT;

CREATE TABLE MEMBER (
	ID VARCHAR2(30) PRIMARY KEY,
	PASSWORD VARCHAR2(30) NOT NULL,
	NAME VARCHAR2(30) NOT NULL,
	EMAIL VARCHAR2(30) NOT NULL,
	ADDRESS VARCHAR2(100) NOT NULL,
	BIRTHDAY VARCHAR2(100) NOT NULL,
	GENDER VARCHAR2(30) NOT NULL,
	PHONE VARCHAR2(50) NOT NULL,
	QUESTION VARCHAR2(200) ,
	HINT VARCHAR2(100) NOT NULL,
	EXHIBIT_NAME VARCHAR2(50),
	CERTI_NUM VARCHAR2(50),
	AUTH NUMBER(8) NOT NULL
);

ALTER TABLE MEMBER
ADD CONSTRAINT UK_MEMBER_EMAIL UNIQUE(EMAIL);

ALTER TABLE MEMBER
ADD CONSTRAINT UK_MEMBER_PHONE UNIQUE(PHONE);

ALTER TABLE MEMBER
ADD CONSTRAINT UK_MEMBER_CERTI_NUM UNIQUE(CERTI_NUM);

SELECT * FROM MEMBER;

INSERT INTO MEMBER
VALUES ('admin', 'admin', '관리자', '0', '0', '0', '0', '0', '0', '0', '0', '0', 3);
















            